import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import Navbar from "./components/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div className="flex flex-col items-center w-full">
            <Navbar className="fixed w-full top-0 z-20" />
            <div className="flex flex-col mt-24 relative items-center min-h-screen gap-4 w-1/3">
              <div className="flex flex-col absolute items-center justify-center w-full min-h-[50vh] bg-text/10 backdrop-blur-2xl">
                {/* Model Container */}
              </div>
              <div className="mt-[45%] z-10 w-[80%]">
                {children}
              </div>
              <footer className="flex flex-row items-center justify-center gap-2 text-sm font-medium text-text/50 mt-auto py-8">
                &copy; {new Date().getFullYear()} Kyle Bolo. All rights reserved.
              </footer>
            </div>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
